package cli

import (
	"fmt"

	"github.com/spf13/cobra"
	"github.com/torchsecurity/torch-secret-analyzer/pkg/cli/aws"
)

var torchCommand = &cobra.Command{
	Use:   "torch",
	Short: "Torch's CLI tool for analyzing secrets",
	Long:  `Torch Secrets Analyzer is a simple (yet powerful!) tool that helps analyze the access to secrets stored in a secrets manager`,
}

func Execute() {
	if err := torchCommand.Execute(); err != nil {
		fmt.Println(err)
	}
}

func init() {
	torchCommand.CompletionOptions.DisableDefaultCmd = true // Disable autogenerated completion commanmd
	torchCommand.AddCommand(aws.AWSCommand)
}
